# These are supported funding model platforms

github: techieanant
# patreon: techieanant
# open_collective: wamr
ko_fi: anantu 
# tidelift: npm/wamr
# custom: ["https://example.com", "https://example2.com"]

# Uncomment and configure the platforms you want to use for sponsorship
