/**
 * Standardized error codes for API responses
 */
export const ErrorCodes = {
  // Authentication & Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  // WhatsApp
  WHATSAPP_NOT_CONNECTED: 'WHATSAPP_NOT_CONNECTED',
  WHATSAPP_CONNECTION_FAILED: 'WHATSAPP_CONNECTION_FAILED',
  WHATSAPP_ALREADY_CONNECTED: 'WHATSAPP_ALREADY_CONNECTED',
  WHATSAPP_INITIALIZATION_FAILED: 'WHATSAPP_INITIALIZATION_FAILED',
  WHATSAPP_SESSION_EXPIRED: 'WHATSAPP_SESSION_EXPIRED',

  // Media Services
  SERVICE_NOT_FOUND: 'SERVICE_NOT_FOUND',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  SERVICE_CONNECTION_FAILED: 'SERVICE_CONNECTION_FAILED',
  INVALID_SERVICE_CONFIG: 'INVALID_SERVICE_CONFIG',
  DUPLICATE_PRIORITY: 'DUPLICATE_PRIORITY',
  NO_ENABLED_SERVICES: 'NO_ENABLED_SERVICES',

  // Requests
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  REQUEST_SUBMISSION_FAILED: 'REQUEST_SUBMISSION_FAILED',
  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',
  INVALID_REQUEST_STATUS: 'INVALID_REQUEST_STATUS',

  // Conversation
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  CONVERSATION_TIMEOUT: 'CONVERSATION_TIMEOUT',
  INVALID_CONVERSATION_STATE: 'INVALID_CONVERSATION_STATE',
  SEARCH_FAILED: 'SEARCH_FAILED',
  NO_RESULTS_FOUND: 'NO_RESULTS_FOUND',
  INVALID_SELECTION: 'INVALID_SELECTION',

  // Database
  DATABASE_ERROR: 'DATABASE_ERROR',
  QUERY_FAILED: 'QUERY_FAILED',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',

  // General
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  BAD_REQUEST: 'BAD_REQUEST',
  CONFLICT: 'CONFLICT',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',

  // Encryption
  ENCRYPTION_ERROR: 'ENCRYPTION_ERROR',
  DECRYPTION_ERROR: 'DECRYPTION_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/**
 * HTTP status codes for error responses
 */
export const HttpStatus = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;
